In [3]:
#import numpy
import numpy as np

In [6]:
#create array
a=np.array([1,2,3,4,7])
b=np.array([[2,3,4],[5,6,7]])
print(a)
print(b)

[1 2 3 4 7]
[[2 3 4]
 [5 6 7]]


In [7]:
#shape of array
print("shape of a is:{}".format(a.shape)) 

shape of a is:(5,)


In [8]:
#dimension of array
print("dim of array is {}".format(a.ndim)) 

dim of array is 1


In [6]:
#size of array
print("size of a is {}".format(a.size)) 

size of a is 5


In [7]:
 #data type of array
print(f"data type of a {a.dtype}")

data type of a int64


In [8]:
#itemsize of array
print(f"itemsize {a.itemsize}") 

itemsize 8


In [9]:
#data memory location of array
print(f"data {a.data}") 

data <memory at 0x7fc12087c640>


In [9]:
#matrix multi of array
a1=np.array([[1,2],[4,5]])
b1=np.array([[9,8],[6,5]])
print(a1)
print(b1)


[[1 2]
 [4 5]]
[[9 8]
 [6 5]]


In [10]:
#dot multiplication
mul=np.dot(a1,b1) 
print(mul)




[[21 18]
 [66 57]]


In [11]:
#sum of all elements of array
print(a.sum()) 

17


In [12]:
a2=np.array([[1,2,3],[4,5,6]])
b2=np.array([[9,8,7],[6,5,4]])
print(a2)
print(b2)


[[1 2 3]
 [4 5 6]]
[[9 8 7]
 [6 5 4]]


In [13]:
#slice of array
sliced_arr=a2[1:,1:]
print(sliced_arr)


[[5 6]]


In [14]:
# add two array
addm=np.add(a1,b1)
print(addm)

[[10 10]
 [10 10]]


In [15]:
# subtract of array
subm=np.subtract(a1,b1)
print(subm)

[[-8 -6]
 [-2  0]]


In [16]:
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(c)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [17]:
# reshape the array of given dimension
re=c.reshape(4,4)
print(re)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
#maximum of array
print("maximum in c is",c.max())
#minimum of array
print("minimum in c is",c.min())
#maximum of array of a row
print("maximum in row is",re.max(axis=1))
#maximum of array of a column
print("minimum in column is",re.min(axis=0))


maximum in c is 16
minimum in c is 1
maximum in row is [ 4  8 12 16]
minimum in column is [1 2 3 4]


In [19]:
d=np.array([[4,8,25],[36,49,64]])
print(d)



[[ 4  8 25]
 [36 49 64]]


In [27]:
#square root of all element
print(np.sqrt(d))
# standard deviation
print("sd",np.std(d))

[[2.         2.82842712 5.        ]
 [6.         7.         8.        ]]
sd 21.33854103103896


In [41]:
a3=np.array([[2,3],[5,6]])
print(a3)
b3=np.array([[4,8],[9,7]])
print(b3)

#merge two array vertically
v=np.vstack((a3,b3))
print(v)
#merge two array horizontally
h=np.hstack((a3,b3))
print(h)
#split vertically merged array
vNew=np.vsplit(v,2)
print(vNew)
#split horizontally merged array
hNew=np.hsplit(v,2)
print(hNew)


[[2 3]
 [5 6]]
[[4 8]
 [9 7]]
[[2 3]
 [5 6]
 [4 8]
 [9 7]]
[[2 3 4 8]
 [5 6 9 7]]
[array([[2, 3],
       [5, 6]]), array([[4, 8],
       [9, 7]])]
[array([[2],
       [5],
       [4],
       [9]]), array([[3],
       [6],
       [8],
       [7]])]


In [35]:
#function that print array from 1 to 20 with gap of 2
arr=np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [36]:
#return range as per given value
arr1=np.arange(0,100,5)
print(arr1)


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [37]:
#function that print array with line space between each other
arr2=np.linspace(0,20,5)
print(arr2)
print(arr2.dtype)

[ 0.  5. 10. 15. 20.]
float64


In [45]:
#return transpose of array
ar=np.array([[25,64,34],[89,36,89]])
print(ar)
dt=ar.T
print(dt)

[[25 64 34]
 [89 36 89]]
[[25 89]
 [64 36]
 [34 89]]


In [46]:
#itterate all element one by one
for i in np.nditer(dt): 
    print("element",i)

element 25
element 64
element 34
element 89
element 36
element 89


In [47]:
Fun=np.array([32,43,87,90])
print(Fun)

[32 43 87 90]


In [59]:
#square root of element
print("Square root : ",np.sqrt(Fun))

Square root :  [5.65685425 6.55743852 9.32737905 9.48683298]


In [61]:
#Returns the standard deviation of in the array
print("Standard Deviation: ",np.std(arr))     

Standard Deviation:  5.744562646538029


In [57]:
#exponentials of element
print("Exponentials: ",np.exp(Fun))     

Exponentials:  [7.89629602e+13 4.72783947e+18 6.07603023e+37 1.22040329e+39]


In [53]:
 # sum of all elements in the array
print("Sum of all element in array: ",np.sum(Fun))    

Sum of all element in array:  252


In [54]:
 #Returns  sin of each element
print("Sin of each element: ",np.sin(Fun))    

Sin of each element:  [ 0.55142668 -0.83177474 -0.82181784  0.89399666]


In [55]:
#Returns the cosine of each element
print("Cos of each element: ",np.cos(Fun))     

Cos of each element:  [ 0.83422336  0.5551133   0.56975033 -0.44807362]


In [62]:
#Returns the logarithm of each element
print("Log: ",np.log(Fun))     

Log:  [3.4657359  3.76120012 4.46590812 4.49980967]


In [64]:
from scipy import stats as st
print("Mean:",np.mean(Fun))

Mean: 63.0


In [66]:
#median of array
print("Median:",np.median(Fun))

Median: 65.0


In [70]:
#mode of array
Fun1=np.array([90,90,32,43,87,90])
print(Fun1)
print("Mode:",st.mode(Fun1))

[90 90 32 43 87 90]
Mode: ModeResult(mode=array([90]), count=array([3]))
